"""add archived_at to classes

Revision ID: 234bcc6ffbe3
Revises: 8f9d9ced554b
Create Date: 2026-08-24 12:37:37.538058

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "234bcc6ffbe3"
down_revision: str | Sequence[str] | None = "8f9d9ced554b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable with no default: every existing class is live, and NULL is what
    # "not archived" means. No index -- a school has tens of classes, and
    # Postgres will sequential-scan the table faster than it can consult one.
    op.add_column("classes", sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("classes", "archived_at")
    # ### end Alembic commands ###
