"""initial schema

Revision ID: 2dccce3fd681
Revises:
Create Date: 2026-08-24 11:02:49.577762

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2dccce3fd681"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=60), nullable=False),
        sa.Column("academic_year", sa.String(length=20), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_classes")),
        sa.UniqueConstraint("name", "academic_year", name="name_year"),
    )
    op.create_table(
        "fee_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("default_amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column(
            "billing_period",
            sa.Enum("term", "monthly", "one_time", name="billing_period"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("default_amount > 0", name=op.f("ck_fee_types_default_amount_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_types")),
        sa.UniqueConstraint("name", name=op.f("uq_fee_types_name")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("role", sa.Enum("admin", "staff", "parent", name="user_role"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target", sa.String(length=120), nullable=True),
        sa.Column("detail", sa.String(length=500), nullable=True),
        sa.Column(
            "timestamp", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_timestamp"), "audit_log", ["timestamp"], unique=False)
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "students",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("last_name", sa.String(length=80), nullable=False),
        sa.Column("admission_number", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum("active", "inactive", name="student_status"),
            server_default="active",
            nullable=False,
        ),
        sa.Column("class_id", sa.Integer(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "length(trim(first_name)) > 0", name=op.f("ck_students_first_name_not_blank")
        ),
        sa.CheckConstraint(
            "length(trim(last_name)) > 0", name=op.f("ck_students_last_name_not_blank")
        ),
        sa.ForeignKeyConstraint(
            ["class_id"],
            ["classes.id"],
            name=op.f("fk_students_class_id_classes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["users.id"],
            name=op.f("fk_students_parent_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_students")),
    )
    op.create_index(
        op.f("ix_students_admission_number"), "students", ["admission_number"], unique=True
    )
    op.create_index(op.f("ix_students_class_id"), "students", ["class_id"], unique=False)
    op.create_index(op.f("ix_students_parent_id"), "students", ["parent_id"], unique=False)
    op.create_table(
        "fee_assignments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("fee_type_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("period_label", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_fee_assignments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["fee_type_id"],
            ["fee_types.id"],
            name=op.f("fk_fee_assignments_fee_type_id_fee_types"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
            name=op.f("fk_fee_assignments_student_id_students"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fee_assignments")),
        sa.UniqueConstraint("student_id", "fee_type_id", "period_label", name="student_fee_period"),
    )
    op.create_index(
        op.f("ix_fee_assignments_fee_type_id"), "fee_assignments", ["fee_type_id"], unique=False
    )
    op.create_index(
        op.f("ix_fee_assignments_student_id"), "fee_assignments", ["student_id"], unique=False
    )
    op.create_table(
        "payments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fee_assignment_id", sa.Integer(), nullable=False),
        sa.Column("amount_paid", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("method", sa.Enum("stripe", "cash", name="payment_method"), nullable=False),
        sa.Column("stripe_payment_intent_id", sa.String(length=255), nullable=True),
        sa.Column("stripe_event_id", sa.String(length=255), nullable=True),
        sa.Column(
            "paid_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("recorded_by_id", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(method = 'stripe' AND stripe_payment_intent_id IS NOT NULL) OR (method = 'cash' AND stripe_payment_intent_id IS NULL)",
            name=op.f("ck_payments_stripe_ids_match_method"),
        ),
        sa.CheckConstraint("amount_paid > 0", name=op.f("ck_payments_amount_paid_positive")),
        sa.ForeignKeyConstraint(
            ["fee_assignment_id"],
            ["fee_assignments.id"],
            name=op.f("fk_payments_fee_assignment_id_fee_assignments"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recorded_by_id"],
            ["users.id"],
            name=op.f("fk_payments_recorded_by_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("stripe_event_id", name="stripe_event_id"),
    )
    op.create_index(
        op.f("ix_payments_fee_assignment_id"), "payments", ["fee_assignment_id"], unique=False
    )
    op.create_index(
        op.f("ix_payments_recorded_by_id"), "payments", ["recorded_by_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_payments_recorded_by_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_fee_assignment_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_fee_assignments_student_id"), table_name="fee_assignments")
    op.drop_index(op.f("ix_fee_assignments_fee_type_id"), table_name="fee_assignments")
    op.drop_table("fee_assignments")
    op.drop_index(op.f("ix_students_parent_id"), table_name="students")
    op.drop_index(op.f("ix_students_class_id"), table_name="students")
    op.drop_index(op.f("ix_students_admission_number"), table_name="students")
    op.drop_table("students")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_timestamp"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("fee_types")
    op.drop_table("classes")
    # ### end Alembic commands ###

    # Autogenerate creates these enum types implicitly with the columns that use
    # them, but never drops them. Without this the downgrade leaves four
    # orphaned types behind and the next upgrade fails on
    # "type ... already exists". Added by hand.
    for enum_name in ("payment_method", "billing_period", "student_status", "user_role"):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
