"""add ip_address to audit_log

Revision ID: 8f9d9ced554b
Revises: 2dccce3fd681
Create Date: 2026-08-24 12:08:28.537362

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8f9d9ced554b"
down_revision: str | Sequence[str] | None = "2dccce3fd681"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_log", sa.Column("ip_address", sa.String(length=45), nullable=True))
    op.create_index(op.f("ix_audit_log_ip_address"), "audit_log", ["ip_address"], unique=False)
    # The login limiter counts failures by account as well as by source.
    op.create_index(op.f("ix_audit_log_target"), "audit_log", ["target"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_log_target"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_ip_address"), table_name="audit_log")
    op.drop_column("audit_log", "ip_address")
    # ### end Alembic commands ###
